//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitMexConnector.UnitTests.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExecutionParserTests {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExecutionParserTests() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BitMexConnector.UnitTests.TestData.ExecutionParserTests", typeof(ExecutionParserTests).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;table&quot;: &quot;execution&quot;,
        ///  &quot;action&quot;: &quot;insert&quot;,
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;execID&quot;: &quot;02042c2a-edf7-7c39-2949-a66be85683a7&quot;,
        ///      &quot;orderID&quot;: &quot;6ab772ce-7279-6ff6-0052-fbf75bc1f670&quot;,
        ///      &quot;clOrdID&quot;: &quot;e3ab7ab8-2cfb-4cb0-bc1a-57cccf9f0cb9&quot;,
        ///      &quot;clOrdLinkID&quot;: &quot;&quot;,
        ///      &quot;account&quot;: 79242,
        ///      &quot;symbol&quot;: &quot;XBTUSD&quot;,
        ///      &quot;side&quot;: &quot;Buy&quot;,
        ///      &quot;lastQty&quot;: 1,
        ///      &quot;lastPx&quot;: 6224.5,
        ///      &quot;underlyingLastPx&quot;: null,
        ///      &quot;lastMkt&quot;: &quot;XBME&quot;,
        ///      &quot;lastLiquidityInd&quot;: &quot;RemovedLiquidity&quot;,
        ///      &quot;simpleOrd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Execution_Insert {
            get {
                return ResourceManager.GetString("Execution_Insert", resourceCulture);
            }
        }
    }
}
