//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitMexConnector.UnitTests.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrderBookL2ParserTests {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderBookL2ParserTests() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BitMexConnector.UnitTests.TestData.OrderBookL2ParserTests", typeof(OrderBookL2ParserTests).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;table&quot;: &quot;orderBookL2&quot;,
        ///  &quot;keys&quot;: [ &quot;symbol&quot;, &quot;id&quot;, &quot;side&quot; ],
        ///  &quot;types&quot;: {
        ///    &quot;symbol&quot;: &quot;symbol&quot;,
        ///    &quot;id&quot;: &quot;long&quot;,
        ///    &quot;side&quot;: &quot;symbol&quot;,
        ///    &quot;size&quot;: &quot;long&quot;,
        ///    &quot;price&quot;: &quot;float&quot;
        ///  },
        ///  &quot;foreignKeys&quot;: {
        ///    &quot;symbol&quot;: &quot;instrument&quot;,
        ///    &quot;side&quot;: &quot;side&quot;
        ///  },
        ///  &quot;attributes&quot;: {
        ///    &quot;symbol&quot;: &quot;grouped&quot;,
        ///    &quot;id&quot;: &quot;sorted&quot;
        ///  },
        ///  &quot;action&quot;: &quot;partial&quot;,
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;symbol&quot;: &quot;XBTUSD&quot;,
        ///      &quot;id&quot;: 1,
        ///      &quot;side&quot;: &quot;Sell&quot;,
        ///      &quot;size&quot;: 1200,
        ///      &quot;price&quot;: 12000
        ///    },   
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrderBookL2_Partial_json {
            get {
                return ResourceManager.GetString("OrderBookL2_Partial.json", resourceCulture);
            }
        }
    }
}
