using System;
using Common.Robots.Common;

namespace BitMexConnector.Tables.Classes
{
    public class BitMexLimitOrder
    {
        /* Generated by client and is being passed during communication
         when set up via web site is empty string */
        public string OrderId { get; set; }
        
        /*  Generated by system  */
        public string SystemOrderId { get; set; }

        public string Symbol { get; set; }

        public double Size { get; set; }

        public double LeftSize { get; set; }

        /*  Market order has null price */
        public double? Price { get; set; }

        public OrderStatuses OrderStatus { get; set; }

        public OrderTypes OrderType { get; set; }

        public OrderSides Side { get; set; }

        public DateTime DateTime { get; set; }
    }
}