using System;
using Common.Robots.Common;

namespace BitMexConnector.Tables.Classes
{
    public class BitMexTrade
    {
        public string TradeId { get; set; }

        public string OrderId { get; set; }
        
        /*  Generated by system  */
        public string SystemOrderId { get; set; }

        public string Symbol { get; set; }

        public double Size { get; set; }

        public OrderSides Side { get; set; }

        public double Price { get; set; }

        public DateTime DateTime { get; set; }

        public double? LeftSize { get; set; }
    }
}