//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UsdRobotTestStrategies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UsdRobotTestStrategies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Robot.UnitTests.UsdRobotTestStrategies", typeof(UsdRobotTestStrategies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Iterations&gt;
        ///  &lt;Iteration index =&quot;0&quot;&gt;
        ///    &lt;ShouldOpen&gt;
        ///      &lt;Direction&gt;Buy&lt;/Direction&gt;
        ///    &lt;/ShouldOpen&gt;
        ///  &lt;/Iteration&gt;
        ///  &lt;Iteration index =&quot;1&quot;&gt;
        ///    &lt;ShouldClose&gt;
        ///      &lt;Direction&gt;Buy&lt;/Direction&gt;
        ///    &lt;/ShouldClose&gt;
        ///  &lt;/Iteration&gt;
        ///&lt;/Iterations&gt;.
        /// </summary>
        internal static string OpenClose {
            get {
                return ResourceManager.GetString("OpenClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Iterations&gt;
        ///  &lt;Iteration index =&quot;0&quot;&gt;
        ///    &lt;ShouldOpen&gt;
        ///      &lt;Direction&gt;Sell&lt;/Direction&gt;
        ///    &lt;/ShouldOpen&gt;
        ///  &lt;/Iteration&gt;
        ///  &lt;Iteration index =&quot;1&quot;&gt;    
        ///    &lt;ShouldOpen&gt;
        ///      &lt;Direction&gt;Buy&lt;/Direction&gt;
        ///    &lt;/ShouldOpen&gt;        
        ///  &lt;/Iteration&gt;
        ///  &lt;Iteration index =&quot;2&quot;&gt;
        ///    &lt;ShouldTakeProfit&gt;
        ///      &lt;Direction&gt;Buy&lt;/Direction&gt;      
        ///    &lt;/ShouldTakeProfit&gt;
        ///  &lt;/Iteration&gt;
        ///  &lt;Iteration index =&quot;3&quot;&gt;
        ///    &lt;ShouldTakeProfit&gt;
        ///      &lt;Direction&gt;Buy&lt;/Direction&gt;
        ///    &lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OpenDownOrderNotExecutedTakeProfitNotExecuted {
            get {
                return ResourceManager.GetString("OpenDownOrderNotExecutedTakeProfitNotExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Iterations&gt;
        ///  &lt;Iteration index =&quot;0&quot;&gt;
        ///    &lt;ShouldOpen&gt;
        ///      &lt;Direction&gt;Sell&lt;/Direction&gt;
        ///    &lt;/ShouldOpen&gt;
        ///  &lt;/Iteration&gt;
        ///  &lt;Iteration index =&quot;1&quot;&gt;
        ///    &lt;ShouldTakeProfit&gt;
        ///      &lt;Direction&gt;Buy&lt;/Direction&gt;      
        ///    &lt;/ShouldTakeProfit&gt;
        ///  &lt;/Iteration&gt;
        ///  &lt;Iteration index =&quot;2&quot;&gt;
        ///    &lt;ShouldAddToPosition&gt;
        ///      &lt;Direction&gt;Sell&lt;/Direction&gt;      
        ///    &lt;/ShouldAddToPosition&gt;
        ///  &lt;/Iteration&gt;
        ///  &lt;Iteration index =&quot;3&quot;&gt;
        ///    &lt;ShouldClose&gt;
        ///      &lt;Direction&gt;Sell&lt;/Directi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OpenDownThenTakeProfitThenAddToPosition {
            get {
                return ResourceManager.GetString("OpenDownThenTakeProfitThenAddToPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Iterations&gt;
        ///  &lt;Iteration index =&quot;0&quot;&gt;
        ///    &lt;ShouldOpen&gt;
        ///      &lt;Direction&gt;Buy&lt;/Direction&gt;
        ///    &lt;/ShouldOpen&gt;
        ///  &lt;/Iteration&gt;
        ///  &lt;Iteration index =&quot;1&quot;&gt;
        ///    &lt;ShouldClose&gt;
        ///      &lt;Direction&gt;Sell&lt;/Direction&gt;
        ///    &lt;/ShouldClose&gt;
        ///  &lt;/Iteration&gt;
        ///&lt;/Iterations&gt;.
        /// </summary>
        internal static string OpenIncorrectCloseDirection {
            get {
                return ResourceManager.GetString("OpenIncorrectCloseDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Iterations&gt;
        ///  &lt;Iteration index =&quot;0&quot;&gt;
        ///    &lt;ShouldOpen&gt;
        ///      &lt;Direction&gt;Sell&lt;/Direction&gt;
        ///    &lt;/ShouldOpen&gt;
        ///  &lt;/Iteration&gt;
        ///  &lt;Iteration index =&quot;1&quot;&gt;
        ///    &lt;ShouldTakeProfit&gt;
        ///      &lt;Direction&gt;Buy&lt;/Direction&gt;      
        ///    &lt;/ShouldTakeProfit&gt;
        ///  &lt;/Iteration&gt;  
        ///  &lt;Iteration index =&quot;2&quot;&gt;
        ///    &lt;ShouldClose&gt;
        ///      &lt;Direction&gt;Buy&lt;/Direction&gt;
        ///    &lt;/ShouldClose&gt;
        ///  &lt;/Iteration&gt;
        ///&lt;/Iterations&gt;.
        /// </summary>
        internal static string OpenSetupTakeProfitCloseTakeProfitShouldBeWithdrawn {
            get {
                return ResourceManager.GetString("OpenSetupTakeProfitCloseTakeProfitShouldBeWithdrawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Iterations&gt;
        ///  &lt;Iteration index =&quot;0&quot;&gt;
        ///    &lt;ShouldOpen&gt;
        ///      &lt;Direction&gt;Buy&lt;/Direction&gt;
        ///    &lt;/ShouldOpen&gt;
        ///  &lt;/Iteration&gt;
        ///  &lt;Iteration index =&quot;1&quot;&gt;
        ///    &lt;ShouldTakeProfit&gt;
        ///      &lt;Direction&gt;Sell&lt;/Direction&gt;
        ///    &lt;/ShouldTakeProfit&gt;
        ///  &lt;/Iteration&gt;
        ///  &lt;Iteration index =&quot;2&quot;&gt;
        ///    &lt;ShouldTakeProfit&gt;
        ///      &lt;Direction&gt;Sell&lt;/Direction&gt;
        ///    &lt;/ShouldTakeProfit&gt;
        ///  &lt;/Iteration&gt;
        ///&lt;/Iterations&gt;.
        /// </summary>
        internal static string OpenThenTakeProfitThenTakeProfitWasWithdrawnThenNewTakeProfit {
            get {
                return ResourceManager.GetString("OpenThenTakeProfitThenTakeProfitWasWithdrawnThenNewTakeProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Iterations&gt;
        ///  &lt;Iteration index =&quot;0&quot;&gt;
        ///    &lt;ShouldOpen&gt;
        ///      &lt;Direction&gt;Buy&lt;/Direction&gt;
        ///    &lt;/ShouldOpen&gt;
        ///  &lt;/Iteration&gt;
        ///  &lt;Iteration index =&quot;1&quot;&gt;
        ///    &lt;ShouldTakeProfit&gt;
        ///      &lt;Direction&gt;Sell&lt;/Direction&gt;      
        ///    &lt;/ShouldTakeProfit&gt;
        ///  &lt;/Iteration&gt;
        ///  &lt;Iteration index =&quot;2&quot;&gt;
        ///    &lt;ShouldAddToPosition&gt;
        ///      &lt;Direction&gt;Buy&lt;/Direction&gt;      
        ///    &lt;/ShouldAddToPosition&gt;
        ///  &lt;/Iteration&gt;
        ///  &lt;Iteration index =&quot;3&quot;&gt;
        ///    &lt;ShouldClose&gt;
        ///      &lt;!-- should present --&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OpenUpThenTakeProfitThenAddToPosition {
            get {
                return ResourceManager.GetString("OpenUpThenTakeProfitThenAddToPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Iterations&gt;
        ///  &lt;Iteration index =&quot;0&quot;&gt;
        ///    &lt;ShouldOpen&gt;
        ///      &lt;Direction&gt;Sell&lt;/Direction&gt;
        ///    &lt;/ShouldOpen&gt;
        ///  &lt;/Iteration&gt;
        ///  &lt;Iteration index =&quot;1&quot;&gt;
        ///    &lt;ShouldOpen&gt;
        ///      &lt;Direction&gt;Sell&lt;/Direction&gt;
        ///    &lt;/ShouldOpen&gt;
        ///  &lt;/Iteration&gt;
        ///  &lt;Iteration index =&quot;2&quot;&gt;
        ///    &lt;ShouldOpen&gt;
        ///      &lt;Direction&gt;Sell&lt;/Direction&gt;
        ///    &lt;/ShouldOpen&gt;
        ///  &lt;/Iteration&gt;
        ///&lt;/Iterations&gt;.
        /// </summary>
        internal static string SeveralOpportunitiesToOpenPositionDownStrategy {
            get {
                return ResourceManager.GetString("SeveralOpportunitiesToOpenPositionDownStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Iterations&gt;
        ///  &lt;Iteration index =&quot;0&quot;&gt;
        ///    &lt;ShouldOpen&gt;
        ///      &lt;Direction&gt;Buy&lt;/Direction&gt;
        ///    &lt;/ShouldOpen&gt;
        ///  &lt;/Iteration&gt;
        ///  &lt;Iteration index =&quot;1&quot;&gt;
        ///    &lt;ShouldOpen&gt;
        ///      &lt;Direction&gt;Buy&lt;/Direction&gt;
        ///    &lt;/ShouldOpen&gt;
        ///  &lt;/Iteration&gt;
        ///  &lt;Iteration index =&quot;2&quot;&gt;
        ///    &lt;ShouldOpen&gt;
        ///      &lt;Direction&gt;Buy&lt;/Direction&gt;
        ///    &lt;/ShouldOpen&gt;
        ///  &lt;/Iteration&gt;
        ///&lt;/Iterations&gt;.
        /// </summary>
        internal static string SeveralOpportunitiesToOpenPositionUpStrategy {
            get {
                return ResourceManager.GetString("SeveralOpportunitiesToOpenPositionUpStrategy", resourceCulture);
            }
        }
    }
}
