//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitMexConnector.UnitTests.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrdersParserTests {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrdersParserTests() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BitMexConnector.UnitTests.TestData.OrdersParserTests", typeof(OrdersParserTests).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;table&quot;: &quot;order&quot;,
        ///  &quot;action&quot;: &quot;insert&quot;,
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;orderID&quot;: &quot;74090a64-09cd-fdea-688b-33ead0387941&quot;,
        ///      &quot;clOrdID&quot;: &quot;client-order-id-1&quot;,
        ///      &quot;clOrdLinkID&quot;: &quot;&quot;,
        ///      &quot;account&quot;: 79242,
        ///      &quot;symbol&quot;: &quot;XBTUSD&quot;,
        ///      &quot;side&quot;: &quot;Buy&quot;,
        ///      &quot;simpleOrderQty&quot;: null,
        ///      &quot;orderQty&quot;: 10,
        ///      &quot;price&quot;: 10500.5,
        ///      &quot;displayQty&quot;: null,
        ///      &quot;stopPx&quot;: 10000.5,
        ///      &quot;pegOffsetValue&quot;: null,
        ///      &quot;pegPriceType&quot;: &quot;&quot;,
        ///      &quot;currency&quot;: &quot;USD&quot;,
        ///      &quot;settlCurrency&quot;: &quot;XBt&quot;,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Orders_Insert {
            get {
                return ResourceManager.GetString("Orders_Insert", resourceCulture);
            }
        }
    }
}
