using System;

namespace Common.Robots.Common
{
    public class LimitOrder
    {
        public LimitOrder()
        {
            Size = 0;
            Price = 0.0;
            Status = OrderStatuses.NotRegistered;
            DateTime = new DateTime(1970, 1, 1);
        }

        /// <summary>
        /// Client Order ID
        /// </summary>
        public string OrderId { get; set; }

        /// <summary>
        /// Order ID generated by trading platform
        /// </summary>
        public string SystemOrderId { get; set; }

        public DateTime DateTime { get; set; }

        public double Price { get; set; }

        public double Size { get; set; }

        public string Symbol { get; set; }

        /// <summary>
        /// Shows how many contracts are not completed yet. 
        /// Initially balance equals size, when order is fully completed balance equals zero.
        /// </summary>
        public double Balance { get; set; }

        public OrderSides OrderSide { get; set; }

        public OrderStatuses Status { get; set; }

        public LimitOrder Clone()
        {
            return new LimitOrder
            {
                OrderId = OrderId,
                SystemOrderId = SystemOrderId,
                OrderSide = OrderSide,
                Symbol = Symbol,
                Status = Status,
                DateTime = DateTime,
                Size = Size,
                Price = Price,
                Balance = Balance
            };
        }

        public override string ToString()
        {
            return $"{SystemOrderId}, {DateTime}, {Status}, {Size}, {Price}";
        }
    }
}